data_dir:
  artifacts: artifacts
  indian_data: artifacts/Cleaned_Indian_Food_Dataset.csv
  metrics: artifacts/metrics.csv
model_names:
  llama2: llama2
data_path:
  llama2_base: artifacts/llama2_base_metrics.json
  llama2_base_prompts: artifacts/llama2_base_prompts.json
test_size:
  test_size: 20